// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmSzNfgvWNZGj-2Fh0IS8c1CYF___GvAw',
    appId: '1:430853844672:web:2f8bc0d863828b35ecc725',
    messagingSenderId: '430853844672',
    projectId: 'pixcraft-4841b',
    authDomain: 'pixcraft-4841b.firebaseapp.com',
    storageBucket: 'pixcraft-4841b.firebasestorage.app',
    measurementId: 'G-5Z6FDR8RQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiwfXFBJmAh_M2UIXOgvIj27UXUVlg1A',
    appId: '1:430853844672:android:44278d538ca6cf73ecc725',
    messagingSenderId: '430853844672',
    projectId: 'pixcraft-4841b',
    storageBucket: 'pixcraft-4841b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADfi8NLTUgXMMndazYj4wMrK2HKhbIVi0',
    appId: '1:430853844672:ios:a044b02abe018c03ecc725',
    messagingSenderId: '430853844672',
    projectId: 'pixcraft-4841b',
    storageBucket: 'pixcraft-4841b.firebasestorage.app',
    iosBundleId: 'com.example.pixcraft',
  );
}
